Script improvements (#546)
* Removed frankfurter scripts from top-level gitignore, added script to copy ssh public key

* Replaced add-ssh-key with ssh-copy-id

* Pruned unused dependencies

* Starting with dongle driver installation

* Added blacklist of unnecessary modules

* add quotes to create_update.sh

* add quotes to deploy_update

* add quotes to install_update

* edit create_update quotes

* add quotes configure.sh

* add quotes interfaces.sh

* add quotes usb-fix.sh

* add quotes usb-fwd.sh

* add quotes bootstrap.sh

* add quotes master_frank_setup

* add quotes start_frank_install

* add quotes update.sh

* edit quotes

* edit quotes install_update

* add quotes env.sh

* more quotes ot usb-fwd.sh

* edit quotes master_frank_setup.sh

* Removed memcached config

* added networking.sh

* Fixed run-remote usage, added DevOps tools to path

* Removed mac address script

* Removed SSHD config

* Removed runtime script, updated unit files

* Added path assertion checks to services, other changes

* Renamed executables to remove extensions

* Rewrote create_update to use in-memory temp directory

* Reimplemented deploy_update using new env source

* Changed install_update to use user-defined systemd services

* Modified and updated log packager

* Added install.service, modified other service targets

* Refactored USB network forwarding script

* Fixed update.sh to work with nested files

* Implemented new autonomous installation process

* Fixed installation issues

* Fixed basic syntax issues

* Fixed issue with oneshot install service terminating early

* Changed install condition to not use first-boot

* Suppressed some unimportant output

* Fixed update issues

* Made update and runtime system services again

* Disabled protobuf compilation by default

* Switch back to ubuntu

* Removed accidental file

* Updated team config for usage of env

* Added protobuf version check

* Fixed IP address for make_team_net

* Added pip package download to create_update

* Fixed Python package inclusion

* Removed Python package inclusion

* Fixed numbering

* Added networking restart/status systemd aliases

* Added wrapper around update

* Fixed DTB recompilation

* Added basic Pipfile

diff --git a/DevOps/frankfurter/scripts/tools/run_remote b/DevOps/frankfurter/scripts/tools/run_remote
--- a/DevOps/frankfurter/scripts/tools/run_remote
+++ b/DevOps/frankfurter/scripts/tools/run_remote
@@ -1,13 +1,12 @@
 #!/bin/bash
 
-# run-remote -- Run any executable on a remote machine.
+# run_remote -- Run an executable on a remote machine.
 
 set -e
-source $(git rev-parse --show-toplevel)/DevOps/frankfurter/scripts/tools/env.sh
+source "$(git rev-parse --show-toplevel)/DevOps/frankfurter/scripts/tools/env"
 
-usage="Run an executable on a Beaglebone remotely.\n\n"
-usage=$usage"Usage:\n"
-usage=$usage"$indent$(basename "$0") [-hvs] <executable>\n\n"
+usage="Run an executable on a remote machine.\n"
+usage=$usage"Usage: $(basename $0) [-hqs] [-u <user>] [-r <host>] <executable>\n\n"
 usage=$usage"Options:\n"
 usage=$usage$indent"-h        Show this help message.\n"
 usage=$usage$indent"-q        Run this script in quiet mode.\n"
@@ -28,14 +27,14 @@ while getopts ":hqsu:r:" opt; do
     u) user="$OPTARG";;
     r) ip="$OPTARG";;
     \?)
-      echo "Invalid option: '-$OPTARG'" >&2
+      echo -e $error"Invalid option: '-$OPTARG'"$clear >&2
       echo -e "Use '-h' to see usage." >&2
-      exit
+      exit 1
       ;;
   esac
 done
 
-ssh-copy-id $ssh_flags "$user@$default_ip" 2>$output
-scp $ssh_flags "${@: -1}" "$user@$default_ip:/tmp/exec" >$output
+ssh-copy-id $ssh_options "$user@$default_ip" 2>$output
+scp $ssh_options "${@: -1}" "$user@$default_ip:/tmp/exec" >$output
 remote_cmd="chmod +x /tmp/exec && $use_sudo /tmp/exec && rm /tmp/exec"
-ssh $ssh_flags -t "$user@$default_ip" "$remote_cmd" 2>$output
+ssh $ssh_options -t "$user@$default_ip" "$remote_cmd" 2>$output
